<?php

return [
	'ToolsetAdvancedExport\Ajax' => __DIR__ . '/controllers/ajax.php',
	'ToolsetAdvancedExport\Api' => __DIR__ . '/controllers/api.php',
	'ToolsetAdvancedExport\ApiHandlers\Api_Handler_Interface' => __DIR__ . '/controllers/api_handler/interface.php',
	'ToolsetAdvancedExport\ApiHandlers\Export_Extra_Wordpress_Data_Raw' => __DIR__ . '/controllers/api_handler/export_extra_wordpress_data_raw.php',
	'ToolsetAdvancedExport\ApiHandlers\Export_Extra_Wordpress_Data' => __DIR__ . '/controllers/api_handler/export_extra_wordpress_data.php',
	'ToolsetAdvancedExport\ApiHandlers\Export_Extra_Wordpress_Data_Json' => __DIR__ . '/controllers/api_handler/export_extra_wordpress_data_json.php',
	'ToolsetAdvancedExport\ApiHandlers\Import_Extra_Wordpress_Data' => __DIR__ . '/controllers/api_handler/import_extra_wordpress_data.php',
	'ToolsetAdvancedExport\ApiHandlers\Import_Extra_Wordpress_Data_Zip' => __DIR__ . '/controllers/api_handler/import_extra_wordpress_data_zip.php',
	'ToolsetAdvancedExport\Customized_Twig_Autoloader' => __DIR__ . '/controllers/customized_twig_autoloader.php',
	'ToolsetAdvancedExport\Customize_Setting' => __DIR__ . '/models/customize_setting.php',
	'ToolsetAdvancedExport\Data_Section' => __DIR__ . '/controllers/data_section.php',
	'ToolsetAdvancedExport\Exporter' => __DIR__ . '/controllers/exporter.php',
	'ToolsetAdvancedExport\Importer' => __DIR__ . '/controllers/importer.php',
	'ToolsetAdvancedExport\IMigration_Data' => __DIR__ . '/models/migration_data/interface.php',
	'ToolsetAdvancedExport\Migration_Data_Nested_Array' => __DIR__ . '/models/migration_data/array.php',
	'ToolsetAdvancedExport\Migration_Data_Portable_Post' => __DIR__ . '/models/migration_data/portable_post.php',
	'ToolsetAdvancedExport\Migration_Data_Raw' => __DIR__ . '/models/migration_data/raw.php',
	'ToolsetAdvancedExport\Migration_Handler_Factory' => __DIR__ . '/controllers/migration_handler_factory.php',
	'ToolsetAdvancedExport\MigrationHandler\IMigration_Handler' => __DIR__ . '/controllers/migration_handler/interface.php',
	'ToolsetAdvancedExport\MigrationHandler\Option_Array' => __DIR__ . '/controllers/migration_handler/option_array.php',
	'ToolsetAdvancedExport\MigrationHandler\Option_Array_Custom' => __DIR__ . '/controllers/migration_handler/option_array_custom.php',
	'ToolsetAdvancedExport\MigrationHandler\Option' => __DIR__ . '/controllers/migration_handler/option.php',
	'ToolsetAdvancedExport\MigrationHandler\Menu' => __DIR__ . '/controllers/migration_handler/menu.php',
	'ToolsetAdvancedExport\MigrationHandler\Widgets' => __DIR__ . '/controllers/migration_handler/widgets.php',
	'ToolsetAdvancedExport\MigrationHandler\Post_Option' => __DIR__ . '/controllers/migration_handler/post_option.php',
	'ToolsetAdvancedExport\MigrationHandler\Settings_Reading' => __DIR__ . '/controllers/migration_handler/settings_reading.php',
	'ToolsetAdvancedExport\MigrationHandler\Customizer' => __DIR__ . '/controllers/migration_handler/customizer.php',
	'ToolsetAdvancedExport\Gui\Page_Import_Export' => __DIR__ . '/controllers/page/import_export.php',
	'ToolsetAdvancedExport\Gui\Page_Tools' => __DIR__ . '/controllers/page/tools.php',
	'ToolsetAdvancedExport\Gui\Toolset_Ie_Section' => __DIR__ . '/controllers/page/toolset_ie_section.php',
];